# Introduction to Python



### Simple Math
Let's get started and use Python as a calculator

In [106]:
print(7 + 10)

17


In [107]:
# Addition 
print(5 + 5)

# Subtraction
print(5 - 5)

# Multiplication
print(3 * 5)

# Division 
print(10 / 2)

# Modulo 
print(18 % 7)

# Exponentiation
print(4 ** 2)

10
0
15
5.0
4
16


In [108]:
# Combining processes
print(4 * (2 ** 8))

1024


### Variables

A variable is specific, case-sensitive name that serves as a placeholder for another value. Every time you use variable name, Python replaces the variable with the actual value. Variables help make your code reproducible and flexible to changes.

Here, we will calculate body mass index (BMI) using BMI = kg/m2

In [109]:
# Weight in kg
weight = 68.2

# Height in meters
height = 1.8

weight
height

weight/(height ** 2)

bmi = weight/(height ** 2)
bmi

print(bmi)

21.049382716049383


In [110]:
type(bmi)

float

### Data Types

# ADD MORE in description

In [111]:
# String - text, use single or double quotes
type("abc")

x = "This is a string"
type(x)
print(type(x))

<class 'str'>


In [112]:
# Float - decimal, real number
type(1.2)

float

In [113]:
# Integer - whole number
type(5)

int

In [114]:
# Booleans - logical values
# Useful to filter data
type(True)
type(False)

bool

In [115]:
# Combining data types that are the same

# Sum of integers
print(2 + 3)

# Sum of strings
print("ab" + "cd")

5
abcd


In Python, to combine data types that are not the same you need to explicitly convert the type to be the same. You can do this by using the following functions:

* `str()` - convert to string
* `int()` - convert to integer
* `float()` - convert to float
* `bool()` - convert to boolean

In [116]:
# Example of combining different data types

two_var = 2

# Wrong
print("I have" + two_var + "ducks")

# Correct
print("I have" + str(two_var) + "ducks")

TypeError: Can't convert 'int' object to str implicitly

In [117]:
# String example
print(("duck " * 2) + "goose")
print("I have " + str(2) + " ducks and " + str(1) + " goose")

# Boolean example
print(True + False)
print(True + False + 5)
print(True + False + bool(5))
print(True + False + bool(0))

# Integer example
print(1 + 2 )
print(1 + 2 + True)
print(1 + 2 + int("5"))

duck duck goose
I have 2 ducks and 1 goose
1
6
2
1
3
4
8


### Lists

Lists are used to store multiple items in a single variable.

There are 4 built-in data types in Python used to store collections of data, all with different qualities and usage.

* **List** is a collection which is ordered and changeable. Allows duplicate members.
* **Tuple** is a collection which is ordered and unchangeable. Allows duplicate members.
* **Set** is a collection which is unordered, unchangeable*, and unindexed. No duplicate members.
* **Dictionary** is a collection which is ordered and changeable. No duplicate members.

***

* Lists are created using square brackets `[]`
* **Ordered**: list items are indexed, the first item has index `[0]`, the second item has index `[1]` and so on
* **Changeable**: list items can be changed, added, and removed after it has been created
* **Duplicates**: lists can have items with the same value

In [118]:
fruit = ["apple", "banana", "cherry", "apple", "cherry", "banana"]
print(fruit)
print(type(fruit))

['apple', 'banana', 'cherry', 'apple', 'cherry', 'banana']
<class 'list'>


In [119]:
list_str = ["apple", "banana", "cherry"]
print(list_str)

list_int = [1, 5, 7, 9, 3]
print(list_int)

list_boo = [True, False, False]
print(list_boo)

['apple', 'banana', 'cherry']
[1, 5, 7, 9, 3]
[True, False, False]


In [120]:
list_combo = ["abc", 34, True, 40, "male"]
print(list_combo)

['abc', 34, True, 40, 'male']


In [121]:
# Find the length of the list
print(len(list_combo))

5


In [156]:
# Fruit variables
apple = 5
banana = 10
cherry = 7

# Fruit list combined
fruits = ["Apples", apple, "Bananas", banana, "Cherries", cherry]
print(fruits)
print(type(fruits))

# Fruit list of lists
fruit_lists = [["Apples", apple],
               ["Bananas", banana],
               ["Cherries", cherry]]
print(fruit_lists)
print(type(fruit_lists))


['Apples', 5, 'Bananas', 10, 'Cherries', 7]
<class 'list'>
[['Apples', 5], ['Bananas', 10], ['Cherries', 7]]
<class 'list'>


### Subsetting Lists

**Zero-based indexing**

The first element in a list has index 0, the second element has index 1, and so on. You can specifically select values from your list by using their index.

`mylist[2]`

In [157]:
fruits

['Apples', 5, 'Bananas', 10, 'Cherries', 7]

In [158]:
len(fruits)

6

In [159]:
fruits[0]

'Apples'

In [160]:
fruits[2]

'Bananas'

In [161]:
# Count backwards using negative indexes
# starts at -1
fruits[-4]

'Bananas'

In [162]:
# Subset and Calculate
app_cher = fruits[1] + fruits[-1]
print(app_cher)

12


### Subsetting Lists

**Slicing**

You can select multiple elements from a list by selecting a range of elements. The result will be a new list of the choosen elements.

`my_list[start:end]`

* **start** index will be included
* **end** index will NOT be included

In [163]:
# Range [inclusive : exclusive]
fruits[0:2]

['Apples', 5]

In [164]:
fruits[:4]

['Apples', 5, 'Bananas', 10]

In [165]:
fruits[4:]

['Cherries', 7]

In [166]:
fruits[2:4]

['Bananas', 10]

In [167]:
# Select all list elements explicitly
fruits[:]

['Apples', 5, 'Bananas', 10, 'Cherries', 7]

In [168]:
# Subset and Calculate
app_cher = fruits[1] + fruits[-1]
print(app_cher)

12


In [169]:
# Subsets lists from lists
fruit_lists

[['Apples', 5], ['Bananas', 10], ['Cherries', 7]]

In [170]:
len(fruit_lists)

3

In [171]:
fruit_lists[2]

['Cherries', 7]

In [172]:
fruit_lists[2][0]

'Cherries'

In [173]:
fruit_lists[1][1]

10

### Manipulating list elements

* Change an element
* Add an element
* Remove an element

In [174]:
fruits

['Apples', 5, 'Bananas', 10, 'Cherries', 7]

In [175]:
# Changing an element
# Single value replacements do not need to be brackets
fruits[1] = 3
print(fruits)

['Apples', 3, 'Bananas', 10, 'Cherries', 7]


In [176]:
fruits[4:] = ["Oranges", 5]
print(fruits)

['Apples', 3, 'Bananas', 10, 'Oranges', 5]


In [177]:
# Adding an element
fruits + ["Cherries"]
print(fruits)

['Apples', 3, 'Bananas', 10, 'Oranges', 5]


In [178]:
fruits_2 = fruits + ["Cherries", 8]
print(fruits_2)

['Apples', 3, 'Bananas', 10, 'Oranges', 5, 'Cherries', 8]


In [179]:
# Removing an element
del(fruits_2[6:])

In [180]:
fruits_2

['Apples', 3, 'Bananas', 10, 'Oranges', 5]

#### Deleting an element of a list

* Deleting an element can be done using the `del()` function. 
* As an element is removed from a list, the indexes of the elements that come after the deleted element all change

In [181]:
# Removing multiple elements
del(fruits_2[2:4])
print(fruits_2)

['Apples', 3, 'Oranges', 5]


In [182]:
del(fruits_2[-1]); del(fruits_2[-1])
print(fruits_2)

### Making copies and the inner workings of python

* Creating a copy of a list by assigning a new variable name only makes a reference to the original list
* Any changes made to either reference will change the original list
* Copying a list must be done explicitly so that the actually list, not the reference, is copied.

In [184]:
# Copying reference for a original list
fruits_copy = fruits_2
print(fruits_copy)

['Apples', 3]


In [185]:
# Change in reference copy
del(fruits_copy[1])
print(fruits_copy)
print(fruits_2)

['Apples']
['Apples']


In [187]:
# New list
mylist = [1, 2, 3, 4, 5]
print(mylist)

[1, 2, 3, 4, 5]


In [190]:
# Copying original list explicitly with [:]
copy_1 = mylist[:]
print(copy_1)

[1, 2, 3, 4, 5]


In [191]:
# Change in new list only
del(copy_1[-2:])
print(copy_1)
print(mylist)

[1, 2, 3]
[1, 2, 3, 4, 5]


In [192]:
# Copying original list explicitly with list()
copy_2 = list(mylist)
print(copy_2)
print(mylist)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


In [193]:
# Change in new list only
del(copy_2[0:2])
print(copy_2)
print(mylist)

[3, 4, 5]
[1, 2, 3, 4, 5]


### Functions

A function is a piece of resuable code that performs a specific task

* `str()`
* `bool()`
* `float()`
* `int()`
* `type()`
* `del()`

Several functions exist to complete the tasks you need. You can search online to find functions built in to Python that you may need. Try searching for "maximum value in a list in python" in your search engine.

Many functions can accept multiple arguments. These can also be found on the help page.

In [210]:
# In Ipython, you can use `?max`
max(mylist)

5

In [214]:
?max

In [212]:
# Use the function `round()`
round(1.2345)

1

In [216]:
help(round)
?round

Help on built-in function round in module builtins:

round(...)
    round(number[, ndigits]) -> number
    
    Round a number to a given precision in decimal digits (default 0 digits).
    This returns an int when called with one argument, otherwise the
    same type as the number. ndigits may be negative.



In [ ]:
round(1.2345, 2)

In [ ]:
# Use the function `sorted()`
help(sorted)

In [207]:
# Make new lists
one = ["d", "e", "f"]
two = ["c", "b", "a"]

# Combine lists into one
three = one + two
print(three)

['d', 'e', 'f', 'c', 'b', 'a']


In [208]:
# Sort the new list
sorted(three)

['a', 'b', 'c', 'd', 'e', 'f']

In [209]:
# Reverse sort the list
sorted(three, reverse = True)

['f', 'e', 'd', 'c', 'b', 'a']

**Objects** - values and data structures in Python, essentially everything. Objects have methods associated, depending on type of object.

**Methods** - call functions that belong to Python objects. They are used with dot notation. Some methods change the object they are called on, and some don't.

* string
    * `capitalize()`
    * `replace()`
    * `upper()`
    * `index()`
* float
    * `bit_length()
    * `conjugate()`
* list
    * `index()`
    * `count()`
    * `append()` - adds an element to a list
    * `remove()` - removes the first element of a list that matches the input

In [229]:
# String methods example
a = "apple"
print(a)

apple


In [233]:
a.capitalize()

'Apple'

In [234]:
# The original value is not changed
print(a)

apple


In [235]:
a.upper()

'APPLE'

In [238]:
a.count("p")

2

In [265]:
a.index("p")

1

In [266]:
a.index("e")

4

In [249]:
# List methods example
colors = ["red", "yellow"]
print(colors)

['red', 'yellow']


In [250]:
colors.append("blue")
print(colors)

['red', 'yellow', 'blue']


In [251]:
colors.sort()
print(colors)

['blue', 'red', 'yellow']


In [264]:
colors.index("red")

1

In [252]:
colors.remove("yellow")
print(colors)

['blue', 'red']


### Packages

* directory of python scripts
* each script is a module
* specify functions, methods, types
* thousands of packages available
    * Numpy
    * Matplotlib
    * Scikit-learn
* install specific packages
    * use `pip` to install packages
    * http://pip.readthedocs.org/en/stable/installing
    * Download `get-pip.py`
    * Terminal
        * `python3 get-pip.py`
        * `pip3 install numpy`
        
* Import the entire package
    * `import numpy`
    * `numpy.array([1, 2, 3])`
    * Making a nickname for imported package
        * `import numpy as np`
        * `np.array([1, 2, 3])`
    * Possible but not recommended: only import one function from a package
        * `from numpy import array`
        * `array([1, 2, 3])`
    * Possible but not recommended: import one function from a package with a nickname
        * `from numpy import array as my_array`
        * `my_array([1, 2, 3])


In [255]:
pi

NameError: name 'pi' is not defined

In [ ]:
import math

In [254]:
math.pi

3.141592653589793

In [263]:
# Find the area of a circle
# A = pi * r ** 2
area = math.pi * (0.5) ** 2
print(area)

0.7853981633974483


### Numpy

Numeric python
- alternative to python list
Installation using terminal `pip3 install numpy`
    
numpy arrays: contain only one type


In [276]:
import numpy as np

In [305]:
# Making lists and np_arrays
py_list = [10, 30, 50]
np_array = np.array([20, 40, 60])

In [306]:
# Determining type for python list
print(py_list)
type(py_list)

[10, 30, 50]


list

In [307]:
# Determining type for numpy array
print(np_array)
type(np_array)

[20 40 60]


numpy.ndarray

In [308]:
# Combine python lists
py_list + py_list

[10, 30, 50, 10, 30, 50]

In [309]:
# Sum of numpy arrays
np_array + np_array

array([ 40,  80, 120])

In [310]:
# Sum of list and array
py_list + np_array

array([ 30,  70, 110])

In [334]:
# Combine python list and array with concatenate
# Sort using list method
cat_array = np.concatenate((py_list, np_array))
print(type(cat))

cat_array.sort()
print(type(cat_array))
print(cat_array)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[10 20 30 40 50 60]


In [ ]:
# Multplying a single value with a numpy array
# Element wise calculation
triple_array = cat_array * 3
print(triple_array)

# New listed sorted
triple_array.sort()
print(triple_array)

In [337]:
# Subsetting for specific index
cat_array[0]

10

In [338]:
cat_array[-1]

60

In [339]:
py_list[0]

10

In [340]:
py_list[-1]

50

In [326]:
# Retrieving array of booleans from condition
cat_array > 35

array([False, False,  True, False,  True,  True], dtype=bool)

In [327]:
cat_array

array([10, 30, 50, 20, 40, 60])

In [328]:
# Subsetting with a condition
cat_array[cat_array > 35]

array([50, 40, 60])

In [344]:
print(py_list)
py_list > 25

[10, 30, 50]


TypeError: unorderable types: list() > int()

In [347]:
py_array = np.array(py_list)
print(py_array)
print(type(py_array))

[10 30 50]
<class 'numpy.ndarray'>


In [348]:
py_array > 25

array([False,  True,  True], dtype=bool)

In [349]:
py_array[py_array > 25]

array([30, 50])

### Numpy Arrays

numpy.ndarray

* numpy package
* n-dimensional array
* can create different dimensions

Attributes - gives you more information about the structure of the data, no parenthesis after attribute
* `shape`

In [466]:
# Make a new list of temps from Orlando, Florida
# First element is day of month in January
# Second element is high temp in F
# 5 rows, 2 columns
temps = [[1, 79],
         [5, 77],
         [10, 79],
         [15, 72],
         [20, 80],
         [25, 55],
         [30, 59]]

In [467]:
import numpy as np

In [468]:
np_temps = np.array(temps)

In [469]:
print(type(np_temps))

<class 'numpy.ndarray'>


In [470]:
# 7 rows, 2 columns
print(np_temps.shape)

(7, 2)


In [471]:
print(np_temps)

[[ 1 79]
 [ 5 77]
 [10 79]
 [15 72]
 [20 80]
 [25 55]
 [30 59]]


In [472]:
# Select the second column, with the temperatures only
np_temps[:, 1]

array([79, 77, 79, 72, 80, 55, 59])

In [473]:
# Select only the temperature for the first day of the month
# First row [0]
# Second column [1]
np_temps[0, 1]

79

In [474]:
# Select only the temperature for the first day of the month
# Last row [-1]
# Second column [1]
np_temps[-1, 1]

59

In [475]:
# Find the minimum value in a column of the array
min(np_temps[:, 1])

55

In [478]:
# Find the maximum value in a column of the array
max(np_temps[:, 1])

80

In [479]:
# Mean of temperatures using numpy mean function
np.mean(np_temps[:, 1])

71.571428571428569

In [480]:
# Median of temperature using numpy median function
np.median(np_temps[:, 1])

77.0

In [481]:
# Standard deviation of temperatures using numpy standard deviation function
# Rounding std output
np.std(np_temps[:, 1])
round(np.std(np_temps[:, 1]))

10.0

### Summary 

* Python is an object oriented language
* Everything is an object
    * integers, strings, lists, arrays, ...
* Objects, including the objects that are the result of an expression, can be stored as a variable
* Lists can be 
